# Generated by Django 6.1 on 2026-08-15 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='registration_number',
        ),
    ]
