# Generated by Django 6.1 on 2026-08-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_studentprofile_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('COORDINATOR', 'Coordinator'), ('ADMIN', 'Admin')], default='STUDENT', max_length=20),
        ),
    ]
