import DashboardLayout from "../../../layouts/DashboardLayout";
import "./AdminReports.css";
import BackButton from "../../../components/common/BackButton/BackButton";

const reports = [
  {
    id: 1,
    report: "CSE Internship Report",
    department: "CSE",
    generatedBy: "Admin",
    date: "25 Jul 2026",
    status: "Generated",
  },
  {
    id: 2,
    report: "ECE Internship Summary",
    department: "ECE",
    generatedBy: "Admin",
    date: "24 Jul 2026",
    status: "Generated",
  },
  {
    id: 3,
    report: "Weekly Progress Report",
    department: "IT",
    generatedBy: "Coordinator",
    date: "23 Jul 2026",
    status: "Pending",
  },
  {
    id: 4,
    report: "Completion Certificate Report",
    department: "AI & DS",
    generatedBy: "Admin",
    date: "22 Jul 2026",
    status: "Generated",
  },
];

const AdminReports = () => {
  return (
    <DashboardLayout>
      <BackButton />

      <div className="admin-reports">

        <div className="page-header">
          <h1>Reports Management</h1>

          <p>
            View and download internship reports.
          </p>
        </div>


        <div className="table-card">

          <table>

            <thead>

              <tr>
                <th>ID</th>
                <th>Report Name</th>
                <th>Department</th>
                <th>Generated By</th>
                <th>Date</th>
                <th>Status</th>
                <th>Action</th>
              </tr>

            </thead>


            <tbody>

              {reports.map((report) => (

                <tr key={report.id}>

                  <td>
                    {report.id}
                  </td>

                  <td>
                    {report.report}
                  </td>

                  <td>
                    {report.department}
                  </td>

                  <td>
                    {report.generatedBy}
                  </td>

                  <td>
                    {report.date}
                  </td>

                  <td>
                    {report.status}
                  </td>

                  <td>

                    <button className="view-btn">
                      View
                    </button>

                    <button className="download-btn">
                      Download
                    </button>

                  </td>

                </tr>

              ))}

            </tbody>

          </table>

        </div>

      </div>

    </DashboardLayout>
  );
};

export default AdminReports;