import DashboardLayout from "../../../layouts/DashboardLayout";
import "./AdminReports.css";
import BackButton from "../../../components/common/BackButton/BackButton";
import { useEffect, useState } from "react";
import { getAdminDashboard } from "../../../services/api";

const initialReports = [
  {
    id: 1,
    report: "CSE Internship Report",
    department: "CSE",
    generatedBy: "Admin",
    date: "25 Jul 2026",
    status: "Generated",
  },
  {
    id: 2,
    report: "ECE Internship Summary",
    department: "ECE",
    generatedBy: "Admin",
    date: "24 Jul 2026",
    status: "Generated",
  },
  {
    id: 3,
    report: "Weekly Progress Report",
    department: "IT",
    generatedBy: "Coordinator",
    date: "23 Jul 2026",
    status: "Pending",
  },
  {
    id: 4,
    report: "Completion Certificate Report",
    department: "AI & DS",
    generatedBy: "Admin",
    date: "22 Jul 2026",
    status: "Generated",
  },
];

const AdminReports = () => {
  const [reports, setReports] = useState(initialReports);

  useEffect(() => {
    getAdminDashboard()
      .then((data) => setReports(data.reports || []))
      .catch(() => setReports([]));
  }, []);

  return (
    <DashboardLayout>
      <BackButton />

      <div className="admin-reports">

        <div className="page-header">
          <h1>Reports Management</h1>

          <p>
            View and download internship reports.
          </p>
        </div>


        <div className="table-card">

          <table>

            <thead>

              <tr>
                <th>ID</th>
                <th>Report Name</th>
                <th>Department</th>
                <th>Generated By</th>
                <th>Date</th>
                <th>Status</th>
                <th>Action</th>
              </tr>

            </thead>


            <tbody>

              {reports.map((report) => (

                <tr key={report.id}>

                  <td>
                    {report.id}
                  </td>

                  <td>{report.report}</td>

                  <td>
                    {report.student || report.department || "--"}
                  </td>

                  <td>
                    {report.generatedBy || "System"}
                  </td>

                  <td>
                    {report.date ? new Date(report.date).toLocaleDateString() : "--"}
                  </td>

                  <td>
                    {report.status}
                  </td>

                  <td>

                    <button className="view-btn" onClick={() => report.file ? window.open(report.file, "_blank", "noopener,noreferrer") : window.alert("No report file is available.")}>
                      View
                    </button>

                    <button className="download-btn" onClick={() => report.file ? window.open(report.file, "_blank", "noopener,noreferrer") : window.alert("No report file is available.")}>
                      Download
                    </button>

                  </td>

                </tr>

              ))}

            </tbody>

          </table>

        </div>

      </div>

    </DashboardLayout>
  );
};

export default AdminReports;