# Generated by Django 6.1 on 2026-08-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='hr_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='internship',
            name='hr_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='internship',
            name='hr_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='internship',
            name='internship_type',
            field=models.CharField(blank=True, choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('HYBRID', 'Hybrid')], max_length=20),
        ),
        migrations.AddField(
            model_name='internship',
            name='stipend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
