# Generated by Django 6.1 on 2026-08-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('OFFER_LETTER', 'Offer Letter'), ('FINAL_REPORT', 'Final Report'), ('CERTIFICATE', 'Certificate')], max_length=30),
        ),
    ]
