# Generated by Django 6.1 on 2026-08-22 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_document_type'),
        ('internships', '0002_internship_company_address_internship_hr_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('skills', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_report', to='documents.document')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_reports', to='internships.internship')),
            ],
        ),
    ]
